// code/pure-studio/src/solid/status/session-status-bar.tsx
import {
  Boxes,
  Bot,
  Brain,
  Circle,
  Clock,
  Cpu,
  DollarSign,
  Loader2,
  ShieldCheck,
  Users,
} from "lucide-solid";
import { For, Show, createMemo, type JSX } from "solid-js";
import type {
  AgentDto,
  CompileMode,
  InteractionRequest,
  LspServerRecord,
  McpServerRecord,
  PermissionMode,
  ProviderRecord,
  RoleRecord,
  RuntimeUsage,
  SessionRecord,
  SessionRuntime,
} from "../../types";

const activeAgentStatuses = new Set(["queued", "running", "waiting"]);
const permissionModes: PermissionMode[] = ["request-approval", "auto-review", "full-access"];
const modes: CompileMode[] = ["auto", "plan"];

export function SessionStatusBar(props: {
  runtime: SessionRuntime | null | undefined;
  providers: ProviderRecord[];
  roles: RoleRecord[];
  permissionMode: PermissionMode;
  currentMode: CompileMode;
  selectedSession: SessionRecord | undefined;
  busy: boolean;
  turnPhase: string | undefined;
  activeInteraction: InteractionRequest | null | undefined;
  turnStartedAt: number | null | undefined;
  mcpServers: McpServerRecord[];
  activeMcpServers: string[];
  lspServers: LspServerRecord[];
  activeLspServers: string[];
  agents: AgentDto[];
  onSetSessionMode: (mode: CompileMode) => void;
  onSavePermissionMode: (mode: PermissionMode) => void;
  onSaveRoles: (roles: RoleRecord[]) => void;
}) {
  const usage = () => props.runtime?.usage ?? null;
  const plannerRole = createMemo(() => props.roles.find((role) => role.key === "planner") ?? props.roles[0]);
  const modelInfo = createMemo(() => findModel(props.providers, plannerRole()?.model ?? usage()?.model ?? ""));
  const contextWindow = createMemo(() => modelInfo()?.contextWindow ?? modelInfo()?.maxContextWindow ?? usage()?.contextWindow ?? null);
  const contextLabel = createMemo(() => `${formatTokenCount(usage()?.latestContextTokens)} / ${formatTokenCount(contextWindow())}`);
  const contextWidth = createMemo(() => `${contextPercent(usage()?.latestContextTokens, contextWindow())}%`);
  const costLabel = createMemo(() => formatCost(usage()));
  const visibleAgents = createMemo(() => props.agents.filter((agent) => activeAgentStatuses.has(agent.status)));
  const capabilityCount = createMemo(() =>
    (props.runtime?.activeSkills.length ?? 0) + props.activeMcpServers.length + props.activeLspServers.length,
  );
  const efforts = createMemo(() => modelInfo()?.reasoningEfforts ?? []);
  const waitingPhase = createMemo(() => activeWaitingPhase(props.activeInteraction));
  const visiblePhase = createMemo(() => waitingPhase() ?? props.turnPhase ?? "idle");

  function selectModel(value: string) {
    const [providerId, model] = value.split("::");
    const role = plannerRole();
    if (!role || !providerId || !model) return;
    const provider = props.providers.find((item) => item.id === providerId);
    const info = provider?.models.find((item) => item.slug === model)
      ?? provider?.defaultModels.find((item) => item.slug === model)
      ?? provider?.customModels.find((item) => item.slug === model);
    const effort = info?.reasoningEfforts.includes(role.effort)
      ? role.effort
      : info?.reasoningEfforts[0] ?? "";
    props.onSaveRoles(props.roles.map((item) =>
      item.key === role.key ? { ...item, provider: providerId, model, effort } : item,
    ));
  }

  function selectEffort(effort: string) {
    const role = plannerRole();
    if (!role) return;
    props.onSaveRoles(props.roles.map((item) => item.key === role.key ? { ...item, effort } : item));
  }

  return (
    <div class="session-status-bar">
      <div class="status-controls">
        <label class="status-select">
          <Show when={props.currentMode === "plan"} fallback={<Bot size={14} />}>
            <Brain size={14} />
          </Show>
          <select
            value={props.currentMode}
            disabled={props.busy || !props.selectedSession}
            onChange={(event) => props.onSetSessionMode(event.currentTarget.value as CompileMode)}
            aria-label="Session mode"
          >
            <For each={modes}>
              {(mode) => <option value={mode}>{mode === "auto" ? "Auto" : "Plan"}</option>}
            </For>
          </select>
        </label>

        <label class="status-select wide">
          <Cpu size={14} />
          <select
            value={`${plannerRole()?.provider ?? ""}::${plannerRole()?.model ?? ""}`}
            onChange={(event) => selectModel(event.currentTarget.value)}
            aria-label="Planner model"
          >
            <For each={props.providers}>
              {(provider) => (
                <optgroup label={provider.name || provider.id}>
                  <For each={allModels(provider)}>
                    {(model) => <option value={`${provider.id}::${model.slug}`}>{model.displayName || model.slug}</option>}
                  </For>
                </optgroup>
              )}
            </For>
          </select>
        </label>

        <Show when={efforts().length > 0}>
          <label class="status-select compact">
            <Clock size={14} />
            <select
              value={plannerRole()?.effort ?? efforts()[0] ?? ""}
              onChange={(event) => selectEffort(event.currentTarget.value)}
              aria-label="Reasoning effort"
            >
              <For each={efforts()}>
                {(effort) => <option value={effort}>{effort}</option>}
              </For>
            </select>
          </label>
        </Show>

        <label class="status-select wide">
          <ShieldCheck size={14} />
          <select
            value={props.permissionMode}
            onChange={(event) => props.onSavePermissionMode(event.currentTarget.value as PermissionMode)}
            aria-label="Permission mode"
          >
            <For each={permissionModes}>
              {(mode) => <option value={mode}>{permissionLabel(mode)}</option>}
            </For>
          </select>
        </label>
      </div>

      <div class="status-readouts">
        <StatusDetails icon={<Clock size={14} />} label={phaseLabel(visiblePhase(), props.turnStartedAt)}>
          <StatusLine label="Phase" value={visiblePhase()} />
          <StatusLine label="Busy" value={props.busy ? "yes" : "no"} />
          <StatusLine label="Blocked" value={waitingPhase() ? "yes" : "no"} />
          <Show when={waitingPhase()}>
            {(phase) => <StatusLine label="Waiting for" value={interactionLabel(phase())} />}
          </Show>
        </StatusDetails>

        <StatusDetails label={contextLabel()}>
          <div class="context-meter"><span style={{ width: contextWidth() }} /></div>
          <StatusLine label="Input" value={formatTokenCount(usage()?.promptTokens)} />
          <StatusLine label="Output" value={formatTokenCount(usage()?.completionTokens)} />
          <StatusLine label="Cache read" value={formatTokenCount(usage()?.cachedPromptTokens)} />
          <StatusLine label="Cache hit" value={formatPercent(usage()?.cacheHitRate)} />
        </StatusDetails>

        <StatusDetails icon={<DollarSign size={14} />} label={costLabel()}>
          <For each={pricedCosts(usage()?.estimatedCosts)}>
            {(cost) => <StatusLine label={cost.currency} value={formatCostNumber(cost.amount)} />}
          </For>
          <Show when={usage()?.hasUnpricedUsage}>
            <StatusLine label="Unpriced" value="yes" />
          </Show>
        </StatusDetails>

        <StatusDetails icon={<Boxes size={14} />} label={String(capabilityCount())}>
          <StatusGroup title="Skills" items={props.runtime?.activeSkills ?? []} />
          <div class="status-list-title">MCP</div>
          <For each={props.mcpServers} fallback={<span class="status-muted">None</span>}>
            {(server) => <McpRow server={server} active={props.activeMcpServers.includes(server.id)} />}
          </For>
          <div class="status-list-title">LSP</div>
          <For each={props.lspServers} fallback={<span class="status-muted">None</span>}>
            {(server) => <LspRow server={server} active={props.activeLspServers.includes(server.id)} />}
          </For>
        </StatusDetails>

        <StatusDetails icon={<Users size={14} />} label={String(visibleAgents().length)}>
          <For each={visibleAgents()} fallback={<span class="status-muted">No active subagents</span>}>
            {(agent) => <AgentRow agent={agent} />}
          </For>
        </StatusDetails>
      </div>
    </div>
  );
}

function StatusDetails(props: { icon?: JSX.Element; label: string; children: JSX.Element }) {
  return (
    <details class="status-details">
      <summary>
        {props.icon}
        <span>{props.label}</span>
      </summary>
      <div class="status-popover">{props.children}</div>
    </details>
  );
}

function StatusLine(props: { label: string; value: string }) {
  return (
    <div class="status-line">
      <span>{props.label}</span>
      <strong>{props.value}</strong>
    </div>
  );
}

function StatusGroup(props: { title: string; items: string[] }) {
  return (
    <div>
      <div class="status-list-title">{props.title}</div>
      <Show when={props.items.length > 0} fallback={<span class="status-muted">None</span>}>
        <For each={props.items}>
          {(item) => <div class="status-list-item">{item}</div>}
        </For>
      </Show>
    </div>
  );
}

function LspRow(props: { server: LspServerRecord; active: boolean }) {
  return (
    <div class="status-list-item">
      <Show when={props.active} fallback={<Circle size={8} class={lspDotClass(props.server)} />}>
        <Loader2 size={12} class="spin" />
      </Show>
      <span>{props.server.displayName}</span>
      <small>{props.server.activityKind === "idle" ? props.server.availabilityKind : props.server.activityKind}</small>
    </div>
  );
}

function McpRow(props: { server: McpServerRecord; active: boolean }) {
  return (
    <div class="status-list-item">
      <Circle size={8} class={mcpDotClass(props.server, props.active)} />
      <span>{props.server.id}</span>
      <small>{props.active ? `${props.server.availabilityKind} active` : props.server.availabilityKind}</small>
    </div>
  );
}

function AgentRow(props: { agent: AgentDto }) {
  return (
    <div class="status-list-item">
      <Circle size={8} class={`agent-dot ${props.agent.status}`} />
      <span title={props.agent.task}>{props.agent.role}: {props.agent.task}</span>
      <small>{agentStatusLabel(props.agent)}</small>
    </div>
  );
}

function findModel(providers: ProviderRecord[], slug: string) {
  for (const provider of providers) {
    const model = allModels(provider).find((item) => item.slug === slug);
    if (model) return model;
  }
}

function allModels(provider: ProviderRecord) {
  const seen = new Set<string>();
  return [...provider.defaultModels, ...provider.customModels, ...provider.models].filter((model) => {
    if (seen.has(model.slug)) return false;
    seen.add(model.slug);
    return true;
  });
}

function formatTokenCount(value: number | null | undefined) {
  if (!value) return "0";
  if (value >= 1_000_000) return `${(value / 1_000_000).toFixed(1)}M`;
  if (value >= 1_000) return `${(value / 1_000).toFixed(1)}k`;
  return String(value);
}

function formatPercent(value: number | null | undefined) {
  if (value === null || value === undefined) return "-";
  return `${Math.round(value * 100)}%`;
}

function contextPercent(tokens: number | null | undefined, contextWindow: number | null | undefined) {
  if (!tokens || !contextWindow) return 0;
  return Math.max(0, Math.min(100, Math.round((tokens / contextWindow) * 100)));
}

function pricedCosts(costs: RuntimeUsage["estimatedCosts"] | undefined) {
  return (costs ?? []).filter((cost) => Number.isFinite(cost.amount));
}

function formatCost(usage: RuntimeUsage | null) {
  const costs = pricedCosts(usage?.estimatedCosts);
  if (costs.length === 0) return usage?.hasUnpricedUsage ? "unpriced" : "no cost";
  return costs.map((cost) => `${cost.currency} ${formatCostNumber(cost.amount)}`).join(" / ");
}

function formatCostNumber(value: number) {
  if (value === 0) return "0";
  if (Math.abs(value) < 0.01) return value.toFixed(4);
  return value.toFixed(2);
}

function permissionLabel(mode: PermissionMode) {
  switch (mode) {
    case "request-approval":
      return "Request approval";
    case "auto-review":
      return "Auto review";
    case "full-access":
      return "Full access";
  }
}

function phaseLabel(phase: string | undefined, startedAt: number | null | undefined) {
  if (!phase || phase === "idle") return "Idle";
  if (isWaitingPhase(phase)) return `Blocked: ${interactionLabel(phase)}`;
  if (!startedAt) return phase;
  const elapsed = Math.max(0, Math.floor(Date.now() / 1000) - startedAt);
  return `${phase} ${elapsed}s`;
}

export type WaitingPhase = "toolApproval" | "userInput" | "planConfirmation";

export function activeWaitingPhase(interaction: InteractionRequest | null | undefined): WaitingPhase | null {
  if (!interaction || interaction.status !== "pending") return null;
  switch (interaction.kind) {
    case "toolApproval":
      return "toolApproval";
    case "userInput":
      return "userInput";
    case "planConfirmation":
      return "planConfirmation";
  }
}

function isWaitingPhase(phase: string): phase is WaitingPhase {
  return phase === "toolApproval" || phase === "userInput" || phase === "planConfirmation";
}

function interactionLabel(phase: WaitingPhase) {
  switch (phase) {
    case "toolApproval":
      return "tool approval";
    case "userInput":
      return "user input";
    case "planConfirmation":
      return "plan confirmation";
  }
}

function lspDotClass(server: LspServerRecord) {
  if (server.availabilityKind === "available") return "lsp-dot available";
  if (server.availabilityKind === "checking") return "lsp-dot checking";
  return "lsp-dot unavailable";
}

function mcpDotClass(server: McpServerRecord, active: boolean) {
  if (active && server.availabilityKind === "available") return "lsp-dot available";
  if (server.availabilityKind === "checking") return "lsp-dot checking";
  return "lsp-dot unavailable";
}

function agentStatusLabel(agent: AgentDto) {
  const cost = formatCost(agent.runtimeUsage ?? null);
  return cost === "no cost" ? agent.status : `${agent.status} / ${cost}`;
}

// code/pure-studio/src/components/SessionStatusBar.tsx
import { Activity, Boxes, Bot, ChevronDown, Cpu, Loader2, ShieldCheck } from "lucide-react";
import type { Dispatch, ReactNode, SetStateAction } from "react";
import { useEffect, useRef, useState } from "react";
import { useTranslation } from "react-i18next";
import type {
  ModelRecord,
  AgentDto,
  AgentStatus,
  ProviderRecord,
  PermissionMode,
  RoleRecord,
  RuntimeCostAmount,
  RuntimeUsage,
  SessionRuntime,
  TurnPhase,
} from "../types";
import { allModels } from "../lib/utils";

type SessionStatusBarProps = {
  runtime: SessionRuntime | null;
  providers: ProviderRecord[];
  roles: RoleRecord[];
  setRoles: Dispatch<SetStateAction<RoleRecord[]>>;
  onSaveProviderSettings: (explicitRoles?: RoleRecord[]) => void;
  onSavePermissionMode: (mode: PermissionMode) => void;
  turnPhase: TurnPhase;
  turnStartedAt: number | null;
  permissionMode: PermissionMode;
  agents: AgentDto[];
};

const turnPhaseKeys: Record<TurnPhase, string> = {
  idle: "turnPhase.idle",
  running: "turnPhase.running",
  thinking: "turnPhase.thinking",
  tool: "turnPhase.tool",
  subagent: "turnPhase.subagent",
  approval: "turnPhase.approval",
  stopping: "turnPhase.stopping",
  completed: "turnPhase.completed",
  aborted: "turnPhase.interrupted",
  interrupted: "turnPhase.interrupted",
  budgetLimited: "turnPhase.budgetLimited",
  errored: "turnPhase.failed",
  failed: "turnPhase.failed",
};

const permissionModes: PermissionMode[] = [
  "workspace-write",
  "request-approval",
  "auto-review",
  "full-access",
];

const activeAgentStatuses = new Set<AgentStatus>([
  "running",
  "waiting",
  "queued",
]);

const agentStatusKeys: Record<AgentStatus, string> = {
  queued: "subagent.queued",
  running: "subagent.running",
  waiting: "subagent.awaitingTool",
  completed: "turnPhase.completed",
  errored: "subagent.failed",
  interrupted: "turnPhase.interrupted",
  shutdown: "status.done",
  notFound: "subagent.notFound",
};

function formatTokenCount(value?: number | null): string {
  const tokens = value ?? 0;
  if (tokens >= 1_000_000) {
    return `${formatNumber(tokens / 1_000_000)}m`;
  }
  if (tokens >= 1_000) {
    return `${formatNumber(tokens / 1_000)}k`;
  }
  return tokens.toString();
}

function formatNumber(value: number): string {
  return Number.isInteger(value) ? value.toFixed(0) : value.toFixed(1);
}

function formatPercent(value?: number | null): string {
  if (value == null) {
    return "0%";
  }
  return `${Math.round(value * 100)}%`;
}

function pricedCosts(costs: RuntimeCostAmount[] | null | undefined): RuntimeCostAmount[] {
  return (costs ?? []).filter((cost) => cost.currency && Number.isFinite(cost.amount));
}

function formatCostNumber(value: number): string {
  const absolute = Math.abs(value);
  if (absolute > 0 && absolute < 0.01) {
    return value.toFixed(4);
  }
  return value.toFixed(2);
}

function formatCostAmounts(
  costs: RuntimeCostAmount[] | null | undefined,
  hasUnpricedUsage: boolean | undefined,
  fallback: string,
  unpriced: string,
): string {
  const priced = pricedCosts(costs);
  if (priced.length === 0) {
    return hasUnpricedUsage ? unpriced : fallback;
  }
  const label = priced
    .map((cost) => `${cost.currency} ${formatCostNumber(cost.amount)}`)
    .join(" + ");
  return hasUnpricedUsage ? `${label} + ${unpriced}` : label;
}

function formatCost(runtime: SessionRuntime | null, fallback: string, unpriced: string): string {
  if (!runtime?.usage) {
    return fallback;
  }
  return formatCostAmounts(
    runtime.usage.estimatedCosts,
    runtime.usage.hasUnpricedUsage,
    fallback,
    unpriced,
  );
}

function formatRuntimeCost(usage: RuntimeUsage | null | undefined, fallback: string, unpriced: string): string {
  if (!usage || usage.totalTokens === 0) {
    return fallback;
  }
  return formatCostAmounts(usage.estimatedCosts, usage.hasUnpricedUsage, fallback, unpriced);
}

function formatElapsed(startedAt: number | null, now: number): string | null {
  if (!startedAt) {
    return null;
  }
  const seconds = Math.max(0, Math.floor((now - startedAt) / 1000));
  if (seconds < 60) {
    return `${seconds}s`;
  }
  const minutes = Math.floor(seconds / 60);
  return `${minutes}m ${seconds % 60}s`;
}

function contextPercent(usage: RuntimeUsage | null): number {
  if (!usage?.contextWindow) {
    return 0;
  }
  return Math.min(100, (usage.latestContextTokens / usage.contextWindow) * 100);
}

function StatusPopover({
  className,
  trigger,
  children,
}: {
  className?: string;
  trigger: ReactNode;
  children: ReactNode;
}) {
  return (
    <div className={`status-popover-wrap ${className ?? ""}`} tabIndex={0}>
      {trigger}
      <div className="status-popover">{children}</div>
    </div>
  );
}

function ListPopover({ title, items }: { title: string; items: string[] }) {
  const { t } = useTranslation();

  return (
    <div className="status-list-popover">
      <strong>{title}</strong>
      {items.length === 0 ? (
        <span className="status-empty">{t("statusBar.notConfigured")}</span>
      ) : (
        items.map((item) => (
          <span key={item} className="status-list-row">
            <span className="status-list-icon">{item.slice(0, 1).toUpperCase()}</span>
            {item}
          </span>
        ))
      )}
    </div>
  );
}

function sortAgents(agents: AgentDto[]): AgentDto[] {
  return [...agents].sort((left, right) => {
    const leftActive = activeAgentStatuses.has(left.status) ? 1 : 0;
    const rightActive = activeAgentStatuses.has(right.status) ? 1 : 0;
    if (leftActive !== rightActive) {
      return rightActive - leftActive;
    }
    if (right.updatedAt !== left.updatedAt) {
      return right.updatedAt - left.updatedAt;
    }
    return left.role.localeCompare(right.role);
  });
}

function TurnStatusIndicator({
  turnPhase,
  turnStartedAt,
}: {
  turnPhase: TurnPhase;
  turnStartedAt: number | null;
}) {
  const { t } = useTranslation();
  const [now, setNow] = useState(Date.now());
  const elapsed = formatElapsed(turnStartedAt, now);
  const isActive = ["running", "thinking", "tool", "subagent", "approval", "stopping"].includes(turnPhase);

  useEffect(() => {
    if (!turnStartedAt || !isActive) {
      return;
    }
    const id = window.setInterval(() => setNow(Date.now()), 1000);
    return () => window.clearInterval(id);
  }, [turnStartedAt, isActive]);

  return (
    <div className={`turn-status-indicator phase-${turnPhase}`} aria-live="polite">
      {isActive ? <Loader2 size={14} className="spin" /> : <Activity size={14} />}
      <strong>{t(turnPhaseKeys[turnPhase])}</strong>
      {elapsed ? <span>{elapsed}</span> : null}
    </div>
  );
}

function AgentPopover({ agents }: { agents: AgentDto[] }) {
  const { t } = useTranslation();
  const items = sortAgents(agents);
  const fallback = t("statusBar.costNotConfigured");
  const unpriced = t("statusBar.costUnpriced");

  return (
    <StatusPopover
      className="subagent-popover-wrap"
      trigger={
        <button className="status-item status-subagents" type="button">
          <Bot size={14} />
          <strong>{t("statusBar.subagents")} {agents.length}</strong>
          <ChevronDown size={13} />
        </button>
      }
    >
      <div className="status-subagent-popover">
        <strong>{t("statusBar.subagents")}</strong>
        {items.length === 0 ? (
          <span className="status-empty">{t("statusBar.noSubagents")}</span>
        ) : (
          items.map((activity) => (
            <div key={activity.id} className={`status-subagent-row status-${activity.status}`}>
              <span className="status-subagent-dot" aria-hidden="true" />
              <div>
                <span className="status-subagent-role">{activity.role}</span>
                <p>{agentPopoverDetail(activity, t)}</p>
              </div>
              <span className="status-subagent-cost">
                {formatRuntimeCost(activity.runtimeUsage, fallback, unpriced)}
              </span>
              <span className="status-subagent-badge">{t(agentStatusKeys[activity.status])}</span>
            </div>
          ))
        )}
      </div>
    </StatusPopover>
  );
}

function agentPopoverDetail(agent: AgentDto, t: (key: string) => string): string {
  if (["errored", "interrupted", "shutdown", "notFound"].includes(agent.status)) {
    if (agent.error?.trim()) {
      return agent.error;
    }
    if (agent.reason?.trim()) {
      return translateAgentReason(agent.reason, t);
    }
  }
  return agent.task;
}

function translateAgentReason(reason: string, t: (key: string) => string): string {
  switch (reason) {
    case "providerError":
      return t("subagent.providerError");
    case "toolError":
      return t("subagent.toolError");
    case "budgetLimited":
      return t("subagent.budgetLimited");
    case "interrupted":
      return t("subagent.interrupted");
    case "shutdown":
      return t("subagent.shutdown");
    default:
      return reason;
  }
}

function CostRows({ usage }: { usage: RuntimeUsage | null }) {
  const { t } = useTranslation();
  const rows = pricedCosts(usage?.estimatedCosts);
  const hasUnpricedUsage = usage?.hasUnpricedUsage ?? false;

  if (rows.length === 0) {
    return (
      <span>
        {t("statusBar.cost")}{" "}
        <strong>{hasUnpricedUsage ? t("statusBar.costUnpriced") : t("statusBar.costNotConfigured")}</strong>
      </span>
    );
  }

  return (
    <>
      {rows.map((cost) => (
        <span className="status-cost-row" key={cost.currency}>
          {cost.currency} <strong>{formatCostNumber(cost.amount)}</strong>
        </span>
      ))}
      {hasUnpricedUsage ? (
        <span className="status-cost-row status-cost-unpriced">
          {t("statusBar.cost")} <strong>{t("statusBar.costUnpriced")}</strong>
        </span>
      ) : null}
    </>
  );
}

function findPlannerRole(roles: RoleRecord[]): RoleRecord | null {
  return roles.find((r) => r.key === "planner") ?? null;
}

function findModelInProviders(
  providers: ProviderRecord[],
  modelSlug: string,
): { provider: ProviderRecord; model: ModelRecord } | null {
  for (const provider of providers) {
    const model = allModels(provider).find((m) => m.slug === modelSlug);
    if (model) return { provider, model };
  }
  return null;
}

function ModelSelector({
  runtime,
  providers,
  roles,
  setRoles,
  onSaveProviderSettings,
}: {
  runtime: SessionRuntime | null;
  providers: ProviderRecord[];
  roles: RoleRecord[];
  setRoles: Dispatch<SetStateAction<RoleRecord[]>>;
  onSaveProviderSettings: (explicitRoles?: RoleRecord[]) => void;
}) {
  const { t } = useTranslation();
  const [open, setOpen] = useState(false);
  const wrapRef = useRef<HTMLDivElement>(null);
  const plannerRole = findPlannerRole(roles);
  const currentModelSlug = plannerRole?.model ?? runtime?.usage.model ?? "";
  const currentModelInfo = findModelInProviders(providers, currentModelSlug);
  const currentEffort = plannerRole?.effort ?? "";
  const currentEfforts = currentModelInfo?.model.reasoningEfforts ?? [];

  useEffect(() => {
    if (!open) return;
    function handleClickOutside(event: MouseEvent) {
      if (wrapRef.current && !wrapRef.current.contains(event.target as Node)) {
        setOpen(false);
      }
    }
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, [open]);

  function buildUpdatedPlannerRole(
    providerId: string,
    modelSlug: string,
    effort: string,
  ): RoleRecord[] {
    return roles.map((r) =>
      r.key === "planner"
        ? { ...r, provider: providerId, model: modelSlug, effort }
        : r,
    );
  }

  function handleSelectModel(providerId: string, modelSlug: string) {
    if (!plannerRole) return;
    const provider = providers.find((p) => p.id === providerId);
    if (!provider) return;
    const model = allModels(provider).find((m) => m.slug === modelSlug);
    if (!model) return;
    const effort = model.reasoningEfforts.includes(currentEffort)
      ? currentEffort
      : (model.reasoningEfforts[0] ?? "");
    const newRoles = buildUpdatedPlannerRole(providerId, modelSlug, effort);
    setRoles(newRoles);
    onSaveProviderSettings(newRoles);
    setOpen(false);
  }

  function handleSelectEffort(effort: string) {
    if (!plannerRole) return;
    const newRoles = roles.map((r) =>
      r.key === "planner" ? { ...r, effort } : r,
    );
    setRoles(newRoles);
    onSaveProviderSettings(newRoles);
  }

  const grouped: { provider: ProviderRecord; models: ModelRecord[] }[] = [];
  for (const provider of providers) {
    const models = allModels(provider);
    if (models.length > 0) {
      grouped.push({ provider, models });
    }
  }

  return (
    <div className="model-selector-wrap" ref={wrapRef}>
      <button
        className="status-item status-model"
        type="button"
        onClick={() => setOpen((v) => !v)}
      >
        <Cpu size={14} />
        <strong>{currentModelInfo?.model.displayName ?? currentModelSlug ?? t("statusBar.noModel")}</strong>
        <ChevronDown size={13} />
      </button>
      {open && (
        <div className="model-selector-dropdown">
          <div className="model-selector-list">
            {grouped.map((group) => (
              <div className="model-selector-group" key={group.provider.id}>
                <div className="model-selector-provider-label">
                  {group.provider.name || group.provider.id}
                </div>
                {group.models.map((model) => (
                  <button
                    key={model.slug}
                    className={`model-selector-option${model.slug === currentModelSlug ? " active" : ""}`}
                    onClick={() => handleSelectModel(group.provider.id, model.slug)}
                  >
                    <span className="model-selector-name">{model.displayName || model.slug}</span>
                    {model.slug === currentModelSlug && currentEfforts.length > 0 ? (
                      <div className="model-selector-efforts" onClick={(e) => e.stopPropagation()}>
                        {currentEfforts.map((effort) => (
                          <button
                            key={effort}
                            className={`model-selector-effort${effort === currentEffort ? " active" : ""}`}
                            onClick={() => handleSelectEffort(effort)}
                          >
                            {effort}
                          </button>
                        ))}
                      </div>
                    ) : null}
                  </button>
                ))}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

export function SessionStatusBar({
  runtime,
  providers,
  roles,
  setRoles,
  onSaveProviderSettings,
  onSavePermissionMode,
  turnPhase,
  turnStartedAt,
  permissionMode,
  agents,
}: SessionStatusBarProps) {
  const { t } = useTranslation();
  const usage = runtime?.usage ?? null;
  const contextLabel = `${formatTokenCount(usage?.latestContextTokens)} / ${formatTokenCount(usage?.contextWindow)}`;
  const costLabel = formatCost(runtime, t("statusBar.costNotConfigured"), t("statusBar.costUnpriced"));
  const contextWidth = `${contextPercent(usage)}%`;
  const skills = runtime?.activeSkills ?? [];
  const mcpServers = runtime?.activeMcpServers ?? [];
  const capabilityCount = skills.length;

  return (
    <div className="session-status-bar" aria-label={t("statusBar.label")}>
      <div className="status-group status-left">
        <TurnStatusIndicator turnPhase={turnPhase} turnStartedAt={turnStartedAt} />
      </div>

      <div className="status-group status-right">
        <ModelSelector
          runtime={runtime}
          providers={providers}
          roles={roles}
          setRoles={setRoles}
          onSaveProviderSettings={onSaveProviderSettings}
        />

        <StatusPopover
          className="context-popover-wrap"
          trigger={
            <button className="status-item status-context" type="button">
              <span>{t("statusBar.context")}</span>
              <strong>{contextLabel}</strong>
              <span className="context-meter" aria-hidden="true">
                <span style={{ width: contextWidth }} />
              </span>
            </button>
          }
        >
          <div className="status-usage-popover">
            <span>
              {t("statusBar.cacheHit")} <strong>{formatPercent(usage?.cacheHitRate)}</strong>
            </span>
            <span>
              {t("statusBar.input")} <strong>{formatTokenCount(usage?.promptTokens)}</strong>
            </span>
            <span>
              {t("statusBar.output")} <strong>{formatTokenCount(usage?.completionTokens)}</strong>
            </span>
            <span>
              {t("statusBar.cacheRead")}{" "}
              <strong>{formatTokenCount(usage?.cachedPromptTokens)}</strong>
            </span>
            <hr />
            <CostRows usage={usage} />
            <small>{t("statusBar.costHint")}</small>
          </div>
        </StatusPopover>

        <StatusPopover
          className="cost-popover-wrap"
          trigger={
            <button className="status-item status-cost" type="button">
              <span>{t("statusBar.cost")}</span>
              <strong>{costLabel}</strong>
            </button>
          }
        >
          <div className="status-usage-popover">
            <CostRows usage={usage} />
            <small>{t("statusBar.costHint")}</small>
          </div>
        </StatusPopover>

        <StatusPopover
          className="permission-popover-wrap"
          trigger={
            <button className="status-item status-permission" type="button">
              <ShieldCheck size={14} />
              <strong>{t(`permissionMode.${permissionMode}`)}</strong>
              <ChevronDown size={13} />
            </button>
          }
        >
          <div className="status-permission-popover">
            <strong>{t("statusBar.permissionMode")}</strong>
            <p>{t(`settings.security.modeDesc.${permissionMode}`)}</p>
            <div className="status-permission-actions" role="group" aria-label={t("statusBar.permissionMode")}>
              {permissionModes.map((mode) => (
                <button
                  key={mode}
                  type="button"
                  className={mode === permissionMode ? "active" : ""}
                  onClick={() => {
                    if (mode !== permissionMode) {
                      onSavePermissionMode(mode);
                    }
                  }}
                >
                  {t(`permissionMode.${mode}`)}
                </button>
              ))}
            </div>
          </div>
        </StatusPopover>

        <StatusPopover
          trigger={
            <button className="status-item status-count" type="button">
              <Boxes size={14} />
              <strong>{t("statusBar.capabilities")} {capabilityCount}</strong>
              <ChevronDown size={13} />
            </button>
          }
        >
          <div className="status-extensions-popover">
            <ListPopover title="Skills" items={skills} />
            <ListPopover title="MCP" items={mcpServers} />
          </div>
        </StatusPopover>

        <AgentPopover agents={agents} />
      </div>
    </div>
  );
}
